services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: history_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: app
      RABBITMQ_DEFAULT_PASS: example
    ports:
      - "5672:5672"
      - "15672:15672"

  history:
    build:
      context: ./history-service
    environment:
      DATABASE_URL: postgresql://postgres:example@postgres:5432/history_db
      RABBITMQ_URL: amqp://app:example@rabbitmq/
    depends_on:
      - postgres
      - rabbitmq

  backend:
    build:
      context: ./backend-service
    environment:
      HISTORY_BASE: http://history:8001
      REDIS_URL: redis://redis:6379/0
      WATCHED_CITIES: "Kyiv,Warsaw,Vilnius"
    depends_on:
      - history
      - redis
    ports:
      - "8000:8000"

  fetcher:
    build:
      context: ./fetcher-service
    environment:
      RABBITMQ_URL: amqp://app:example@rabbitmq/
      WATCHED_CITIES: "Kyiv,Warsaw,Vilnius"
      POLL_INTERVAL_SECONDS: "3600"
      MIN_RECORD_INTERVAL_SECONDS: "3000"
    depends_on:
      - rabbitmq
    ports:
      - "8002:8002"

  ui:
    build:
      context: ./ui-service
    environment:
      BACKEND_HOST: backend
    depends_on:
      - backend
    ports:
      - "8080:80"

volumes:
  pgdata:
