services:
  backend:
    build:
      context: ../../backend-service
    image: backend-service
    restart: unless-stopped
    environment:
      HISTORY_BASE: ${HISTORY_BASE}
      REDIS_URL: ${REDIS_URL}
      WATCHED_CITIES: ${WATCHED_CITIES}
    ports:
      - "8000:8000"
