# SPDX-License-Identifier: GPL-2.0-or-later
---
ingress:
  enabled: true
  ingressClassName: traefik
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
    traefik.ingress.kubernetes.io/router.middlewares: headlamp-internal-only@kubernetescrd

resources:
  requests:
    cpu: 10m
    memory: 64Mi
  limits:
    memory: 256Mi
