# SPDX-License-Identifier: GPL-2.0-or-later
---
alertmanager:
  enabled: false

kubeControllerManager:
  enabled: false
kubeScheduler:
  enabled: false
kubeProxy:
  enabled: false
kubeEtcd:
  enabled: false

defaultRules:
  rules:
    etcd: false
    kubeControllerManager: false
    kubeProxy: false
    kubeSchedulerAlerting: false
    kubeSchedulerRecording: false
    windows: false

prometheus:
  ingress:
    enabled: true
    ingressClassName: traefik
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: web
      traefik.ingress.kubernetes.io/router.middlewares: monitoring-internal-only@kubernetescrd
    paths:
      - /
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false
    ruleSelectorNilUsesHelmValues: false
    retention: 3d
    retentionSize: 4GB
    resources:
      requests:
        cpu: 100m
        memory: 400Mi
      limits:
        memory: 1Gi
    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 5Gi

grafana:
  admin:
    existingSecret: grafana-admin
  ingress:
    enabled: true
    ingressClassName: traefik
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: web
      traefik.ingress.kubernetes.io/router.middlewares: monitoring-internal-only@kubernetescrd
  grafana.ini:
    plugins:
      preinstall_disabled: true
  resources:
    requests:
      cpu: 20m
      memory: 256Mi
    limits:
      memory: 1Gi

prometheusOperator:
  resources:
    requests:
      cpu: 20m
      memory: 64Mi

kube-state-metrics:
  resources:
    requests:
      cpu: 10m
      memory: 32Mi

prometheus-node-exporter:
  resources:
    requests:
      cpu: 10m
      memory: 24Mi
