# SPDX-License-Identifier: GPL-2.0-or-later
---
deployment:
  kind: DaemonSet

updateStrategy:
  type: RollingUpdate
  rollingUpdate:
    maxUnavailable: 1
    maxSurge: 0

ports:
  web:
    hostPort: 80
  websecure:
    hostPort: 443

service:
  spec:
    type: ClusterIP

ingressClass:
  enabled: true
  isDefaultClass: true

providers:
  kubernetesCRD:
    enabled: true
  kubernetesIngress:
    enabled: true
    publishedService:
      enabled: false

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    memory: 256Mi
