# SPDX-License-Identifier: GPL-2.0-or-later
---
ports:
  web:
    hostPort: null
    expose:
      default: true
      internal: true
  websecure:
    hostPort: null
    expose:
      default: true
      internal: true

service:
  spec:
    type: LoadBalancer
    externalTrafficPolicy: Local
  additionalServices:
    internal:
      spec:
        type: LoadBalancer
        externalTrafficPolicy: Local

providers:
  kubernetesIngress:
    publishedService:
      enabled: true
