services:
  fetcher:
    build:
      context: ../../fetcher-service
    image: fetcher-service
    restart: unless-stopped
    environment:
      RABBITMQ_URL: ${RABBITMQ_URL}
      WATCHED_CITIES: ${WATCHED_CITIES}
      POLL_INTERVAL_SECONDS: ${POLL_INTERVAL_SECONDS}
      MIN_RECORD_INTERVAL_SECONDS: ${MIN_RECORD_INTERVAL_SECONDS}
    ports:
      - "8002:8002"
