# SPDX-License-Identifier: GPL-2.0-or-later
---
kube_context_source: "{{ oilscope_kubeconfig }}"

kube_context_target: "{{ lookup('ansible.builtin.env', 'HOME') ~ '/.kube/config' }}"
kube_context_enabled: >-
  {{ lookup('ansible.builtin.env', 'OILSCOPE_SET_CONTEXT') | default('true', true) | bool }}
